language: go
# see https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments
# for the detail
sudo: requried
dist: trusty

before_install:
  - sudo apt-get update -qq
  - go get github.com/golang/dep/...

install:
  - $GOPATH/bin/dep ensure
  - go get -u golang.org/x/lint/golint

before_script:
  - golint ./cmd/route-overwrite/... | xargs -r false

script:
  - ./build_linux.sh
  - ./test_linux.sh

deploy:
  provider: script
  api_key:
    secure: "$GITHUB_TOKEN"
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v[0-9].*$"
  skip_cleanup: true
